# Generated by Django 3.0.8 on 2023-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='ishberuvchi',
            name='rasm',
            field=models.ImageField(upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='xizmatlar',
            name='rasm',
            field=models.ImageField(upload_to='restaurants/'),
        ),
    ]
