# Generated by Django 3.0.8 on 2023-03-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20230227_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xizmatlar',
            name='davomiyligi',
        ),
        migrations.RemoveField(
            model_name='xizmatlar',
            name='xturi',
        ),
        migrations.DeleteModel(
            name='IshBeruvchi',
        ),
        migrations.DeleteModel(
            name='Xizmatlar',
        ),
        migrations.DeleteModel(
            name='XizmatTuri',
        ),
        migrations.DeleteModel(
            name='XizmatVaqti',
        ),
    ]
