# Generated by Django 3.0.8 on 2023-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20230305_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='eskin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
