# Generated by Django 3.0.8 on 2023-03-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant1',
            old_name='categories',
            new_name='categories1',
        ),
    ]
