# Generated by Django 3.0.8 on 2023-03-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20230302_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.FileField(upload_to='restaurants/')),
                ('malumot', models.CharField(max_length=200)),
            ],
        ),
    ]
