# Generated by Django 3.0.8 on 2023-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_reklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant1',
            name='aloqa',
        ),
        migrations.RemoveField(
            model_name='restaurant1',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurant1',
            name='narxi',
        ),
        migrations.AddField(
            model_name='restaurant1',
            name='file',
            field=models.FileField(default=1, upload_to='restaurants/'),
            preserve_default=False,
        ),
    ]
